# Dependencies
markdown: kramdown
highlighter: rouge

plugins:
    - jekyll-sitemap

# File rules
exclude: [vendor, Dangerfile, Gemfile, Gemfile.lock, LICENSE, README.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, new_draft.sh]

# Permalinks
permalink: /:title/

# Site
title: 'KotWek'
description: 'A community-driven weekly newsletter about Kotlin'
url: https://dennisotugo.github.io/KotlinNigeria-Newsletter/
logo: /img/logo.png
timezone: Africa/Lagos

twitter:
    username: kotlinnigeria

# Setup
excerpt_separator: <!--excerpt-->

# Data
links:
    rss: '/feed.xml'
    twitter: 'https://twitter.com/kotlinnigeria'
    github: 'https://github.com/KotlinNigeria/KotlinNigeria-Newsletter'
    issue: 'https://github.com/KotlinNigeria/KotlinNigeria-Newsletter/issues/new'
    pull: 'https://github.com/KotlinNigeria/KotlinNigeria-Newsletter/compare'
    applenews: '/'
