# Dependencies
markdown: kramdown
highlighter: rouge

plugins:
    - jekyll-sitemap

# File rules
exclude: [vendor, Dangerfile, Gemfile, Gemfile.lock, LICENSE, README.md, CODE_OF_CONDUCT.md, CONTRIBUTING.md, new_draft.sh]

# Permalinks
permalink: /:title/

# Site
title: 'Swift Weekly Brief'
description: 'A community-driven weekly newsletter about Swift.org'
url: https://dennisotugo.github.io/KotlinNigeria-Newsletter/
logo: /img/logo.png
timezone: Africa/Lagos

twitter:
    username: swiftlybrief

# Setup
excerpt_separator: <!--excerpt-->

# Data
links:
    rss: '/feed.xml'
    twitter: 'https://twitter.com/kotlinniger'
    github: 'https://github.com/dennisotugo/KotlinNigeria-Newsletter/'
    issue: 'https://github.com/dennisotugo/KotlinNigeria-Newsletter/issues/new'
    pull: 'https://github.com/dennisotugo/KotlinNigeria-Newsletter/compare'
    applenews: '/'
